name: Bug faction
description: Report un bug du plugin faction
title: '[Bug][Faction]: '
assignees:
  - Zeldown
  - aureliancnx
labels:
  - bug
  - faction
  - ' triage'
body:
  - type: input
    id: pseudo
    attributes:
      label: Pseudo InGame
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      description: Dites-nous ce qui est arrivé
    validations:
      required: true
  - type: textarea
    id: what-should-happened
    attributes:
      label: 'Qu''aurait-il dû arriver ?'
  - type: dropdown
    id: server
    validations:
      required: true
    attributes:
      label: Serveur
      description: Sur quel serveur est-ce arrivé ?
      options:
        - Global
        - Minage
        - Soleratl
        - Muzdan
        - Manashino
        - Naera
        - Rakavi
        - Luccento
        - Imbali
        - Keltis
        - Neolith
        - Untaa
  - type: input
    id: date
    attributes:
      label: Date et heure de la production du bug
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Bug du plugin Faction
      options:
        - label: Le bug que je signale concerne **uniquement** un bug du plugin Factions
          required: true
  - type: input
    id: os
    attributes:
      label: 'Système d''exploitation'
      description: Quel est votre système d'exploitation ? Windows, Linux, Mac
  - type: input
    id: ram
    attributes:
      label: Ram
      description: Combien avez-vous de giga de Ram ?
  - type: input
    id: cg
    attributes:
      label: Carte Graphique
      description: 'Quelle carte graphique avez-vous ?'
  - type: textarea
    id: log
    attributes:
      label: LOG
      description: Si vous avez des logs à nous fournir, c'est ici !
