name: FeedBack
description: Faire un retour sur une feature
title: '[FeedBack]: '
labels:
  - bug
  - ' triage'
body:
  - type: input
    id: pseudo
    attributes:
      label: Pseudo InGame
    validations:
      required: true
  - type: input
    id: featureName
    attributes:
      label: Nom de la feature
    validations:
      required: true
  - type: textarea
    id: feedback
    attributes:
      label: Retour sur la Feature 
      description: Qu''es-ce qui pourrais être améliorer ! 
    validations:
      required: true
