name: Bug report
description: Report un bug
title: '[FeedBack]: '
labels:
  - bug
  - ' triage'
assignees:
  - Zeldown
  - goldorak85
  - aureliancnx
  - terrainwax
body:
  - type: input
    id: pseudo
    attributes:
      label: Pseudo InGame
    validations:
      required: true
  - type: input
    id: featureName
    attributes:
      label: Nom de la feature
    validations:
      required: true
  - type: textarea
    id: feedback
    attributes:
      label: Retour sur la Feature 
      description: Qu''es-ce qui pourrais être améliorer ! 
    validations:
      required: true
